name: 'Clickup Task Creator'
description: 'To create clickup incidents out of dependabot alerts'

inputs:
  clickup_api_token:
    description: 'Clickup API Token for Security Incidents space'
    required: true
  pull_request_title:
    description: 'PR Title to create clickup task with'
    required: true
  team_id:
    description: 'Deriv Team ID'
    required: true
  list_id:
    description: 'Dependabot Incident List ID'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'