name: Add Secure Code Warrior contextual training to SARIF

on:
  pull_request:

jobs:
  add_sarif_contextual_training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add Secure Code Warrior contextual training to SARIF
      uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1.11
